- name: 'Como crear un containerner y realizar un push a Azure en el Container Registry'
  hosts: localhost

  tasks:
  
  - name: 'Login'
    containers.podman.podman_login:
      username: containerRegistrylg
      password: 'cUZNbX5p2NzhIKIXuns+iYU9vQAArRgN0cW7yJB/52+ACRDy8tfk'
      registry: containerregistrylg.azurecr.io
      
  - name: 'Build and Push an image'
    containers.podman.podman_image:
      name: containerregistrylg.azurecr.io/webserver:container_ansible
      path: /home/webserver/
      push: yes
      push_args:
        dest: containerregistrylg.azurecr.io/webserver:container_ansible
