- name: 'Despliegue en Kubernetes'
  hosts: localhost
  
  vars_files:
    - vars/vars.yaml

  tasks:
    - name: 'Definir los objectos deployment y servicios'
      template:
        src: templates/stateless.j2
        dest: "{{ directorio_trabajo }}/{{ aplicacion.definicion }}"

    - name: 'Crear el namespace de trabajo'
      kubernetes.core.k8s:
        kind: Namespace
        #name: "{{ k8s_namespace }}"
        state: present
        api_version: v1
        
    - name: 'Crear Volumen Persistente'
      kubernetes.core.k8s:
        state: present
        namespace: "{{ k8s_namespace }}"
        definition:
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: task-pv-volume
            labels:
              type: local
          spec:
            storageClassName: manual
            capacity:
              storage: 10Gi
            accessModes:
              - ReadWriteOnce
            hostPath:
              path: "/mnt/data"
