- name: 'Deploy container to AZURE VM'
  hosts: AZURE_VM

  tasks:
  - name: 'Login'
    containers.podman.podman_login:
      username: containerRegistrylg
      password: 'cUZNbX5p2NzhIKIXuns+iYU9vQAArRgN0cW7yJB/52+ACRDy8tfk'
      registry: containerregistrylg.azurecr.io
      
  - name: 'Pull image from AZURE Container Registry'
    containers.podman.podman_image:
      name: containerregistrylg.azurecr.io/webserver
      tag: container_ansible
      state: build
      
  - name: 'Create a container'
    containers.podman.podman_container:
      name: web
      image: containerregistrylg.azurecr.io/webserver:container_ansible
      ports:
        - "8080:443"
      state: started
